version: '2.1'

services:
  yolo-service:
    build: .
    image: doorman/yoloapi:64
    ports:
      - 5001:5001
    volumes:
      - .:/src/app
    links:
      - redis
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - THROTTLE_SECONDS=1
      - DETECT_API_USERNAME=api
      - DETECT_API_PASSWORD=badpassword

  redis:
    image: redis
